---
title: "Introduction to Data Analytics Lecture 2"
author: "Jim Leach"
date: "15 October 2015"
output: pdf_document
---

# Motivation

> Managers do not motivate, they simply tap in to existing motivations.

There are many possible motivations, which can be distinct or overlapping, e.g.

* Fear
* Adulation / respect
* Recognition
* Money
* Enjoyment / personal reward

Managers need to tap in to individuals' drive, persistence, attitude, curiosity, interest, opportunities, talent etc in order to activate their movtivation(s).

## Classical motivation theories:

1. Maslow's Heirarchy of needs. Pyramid structure of needs with most basic (e.g. food, shelter) at the base and more esoteric (e.g. personal contentment) further up. This theory states that unless a company is allowing an employee to meet basic needs (e.g. by paying a living wage) then they cannot expect them to be motivated to perform well.

2. Vroom's Expectancy theory. States that motivation is due to the expectation of a reward. A simply formula is that $Effort -> performance -> reward$. That is, an individual expects that incresed effort will increase performance which, in turn, will induce or will increase the available reward. It is management's "job" to remove doubts at each step to allow employees to make an accurate calculation about this process. E.g. a manager asks an employee to make 100 items in 10 hours for £100. However, the employee thinks they can make only 90 in 10 hours, but could make 100 if they exerted a little more effort. If the manager is clear as to how the promised reward (£100) will be paid if fewer than 100 items are paid, then the employee can make a decision about how to act.

3. Herzberg's Demotivators principle. States that there are factors in the environment that can act as motivators that encourage effort. This can include thins such as challenging work, recognition of achievemnt, opportunties, decision making, or a sense of importance. "Hygeine factors" inclusing status, job-security, work conditions, benefits, salary etc are demotivators that, when absent, undermine performance. Hygiene factors are _extrinsic_ to the work itself and are generally though of as the incentives to induce performance.

## Goals

Are often used as a motivational tool. This includes stretch goals and competition which can help induce people to extra effort and yield increased performance. 

However, management must be careful that goals are constructed carefully such that they do no incentivise short-cuts or cheating.

Management must also be exceptionally clear on what their goals are, and how their reward schemes align with this. I.e., managers must avoid "rewarding for A whilst expecting B" (Kerr).

It is often the case employees are motivated by more than just money and managers must be aware of this when setting goals, and when allocating rewards to meeting goals.

## More on motivation

The wrong kind of praise can be harmful - e.g. if praise is given for _success_ rather than _effort_, it is likely that individuals will only act in scenarios in which they are more certain of succeeding, even if they could be more effective elsewhere. 

Praising for effort, rather than success, can be a better route to help motivate people to try/put in the effort for complex work. It is important to cultivate a _growth_ mindset to encourage people to try new things that they may be uncertain of. This is relevant both up and down the leadership heirarchy.