---
title: "Visualisation Assignment 1a"
author: "Jim Leach"
date: "3 February 2016"
output: word_document
---

# Introduction

## Background

This assignment deals with the curiosities, circumstances, purpose and ideas potentially involved in creating a visualisation/infographic in a number of different scenarios. Four scenarios were considered, each dealing with data on capital punishment/executions in the state of Texas. Representative data were provided and the challenge was to consider these data and the various factors involved in formulating the brief for a visualisation across a number of situations.

## Document structure

This document presents the responses for section 1a of the first assignment for the BS1907 Visualisation module. The document is divided in to sections, one for each of the scenarios in the assignment. Each section is further divided in to sub-sections for the various tasks in the assignment.

# Section 1 - Scenario A

## The scenario

This scenario imagines that we are working for a pro-capital punishment US newspaper reporting on a milestone execution (the 500th) in Texas. 

## General assumptions

I have assumed that the paper is well known for being pro-capital punishment. Additionally, I made a further assumption that the readership shares this view in general. I made a further assumption that part of the reason for the pro-capital punishment stance is a belief that it is an effective deterrent, and that part of it is due to a belief that it is a just punishment for the severity of the crimes involved. I have also assumed that this is not a large, national newspaper, probably something limited to just Texas, or perhaps to just several counties within Texas (given the state's large size).

## Context

### Reason

Within this scenario, I imagined that the following two types of intrigue might present (a) reason(s) for creating the visualisation. 

* __Audience intrigue__: I imagined that the audience might ask "how many victims have there been relative to the number of offenders?", leading in to the (more hypothetical) "how many lives are potentially being saved each year due to deterrent effects?".

* __Anticipated intrigue__: An alternative is to consider readers who are not known to be strictly pro-capital punishment (but who are not anti-execution either). In this instance, the newspaper may want to make a similar case - visualising the number of victims over time for the 500 offenders executed to date. I imagined that the newspaper would think "[our readers] might like to know how many lives have been taken by offenders to date, and how many more might be lost if the deterrent effect was removed". Similarly, the newspaper might try to include in these numbers not just direct victims, but also injured parties, family members effected etc to consider that "[our readers] might be interested in the huge number of people negatively affected by the crimes of these offenders."

### Circumstances

* __Stakeholders__: I thought that the newspaper owner(s) and (senior) editors would be stakeholders as they have an interest in both the work and also in promoting and protecting the newspaper's interests (financial and otherwise). Similarly, the Texas Department of Justice and/or police force may also be stakeholders if quotes/clarification(s)/further data are required for the piece. Similarly, representatives from other pro-capital punishment groups might also be involved if wider information is sought. Finally, the readers of the paper are also stakeholders in the sense that they are financial contributors to the paper, and the piece should entice them to continue to purchase the paper for their news. 

* __Audience__: I assumed that audience is the "average Joe", perhaps non-academic and maybe working class (I imagined the paper to be similar to UK "red-tops"). Overall I have assumed that the audience is not particularly sophisticated and read the paper for news and stories, rather than detailed analysis. I have assumed that, being a newspaper, the audience is relatively captivated: they are willing to sit and read an interesting story for several minutes rather than glancing at something on a poster or in the paper as part of a busy commute.

* __Pressures__: I assumed that, given the scheduled nature of executions, the paper was given around 2 months to produce the piece. No extra financial budget has been given and so the piece forms part of "business as usual".

* __Rules__: The piece needs to be tied to the newspaper's style, but must also be visually striking. As such, a broader colour palette has been permitted, but must be relatively muted and no more than 4 colours can be used in the visualisation. The font used in the piece is restricted to the newspapers in-house font used in all work. The work must be suitable for printing (hence the limited colour palette) and as such should not contain too many small/detailed points/marks that may not be clear in a print version.

* __Frequency__: This is a one-off piece of work for a special feature in the paper. It will not be live and will only focus on data from the first to the 500th execution. Future data will not be incorporated in to the piece as they become available.

* __Setting__: I assumed that the setting is relatively prolonged: the audience will take time to read over the piece as a whole and we do not need something that can be digested in 5 seconds (although considering the non-sophisticated audience it should not be a complex visual that takes a long time to comprehend). The audience is remote - we may need to add explanation(s) and call outs to anything we want to explain in more detail.

* __Size__: The visualisation(s) are to accompany a two-page spread special feature. There needs to be one main visualisation that covers half to one full page of the spread. The data may be used to create either one or two profiles of particularly vicious offenders but these will not require much more that data extracts and quick summaries in terms of the visualisation. Each of these profiles will be at most one eighth of a page each.

* __Format__: The visualisation is print-based. It must be formatted within the constraints set out in "rules" and "size" and is entirely static in nature. 

* __Creators__: The visualisation will be created by a small team comprising of a single journalist with data manipulation skills supported by an illustrator/designer and a team lead/project manager/senior journalist.

* __Tech__: The team does not have a great deal of advanced technical expertise on the data side, and so technology will be focused on Excel and/or other GUI-based tools for data manipulation and preparation. The same case applies for creating the visualisation, however the illustrator/designer is proficient with artistic software (e.g. Photoshop/Illustrator) and can take a basic visualisation and transform it in to the finished product.


## Vision

### Purpose

* __Experience__: The experience should be explanatory. The newspaper is seeking to present the data alongside a compelling written story for the special feature. Given the non-sophisticated audience, it may be necessary to add explanation of anything that is complex. Some of the explaining will be done in the article, but call outs on the visual that references anything contained in the written piece to could help to emphasise this.

* __Tone__: The tone is very much feeling. This is an emotive subject and the type of newspaper is such that an emotive message will be most effective for communicating the intended message/understanding of the data to the audience. Too many dry facts will not help sell the newspaper, and they may be seeking to (further) convince readers that capital punishment is the right choice. As such, a "feeling" tone is most appropriate. 

## Ideas

Please note that the victims vs. criminals idea in this section was inspired by the main graphic in the Wall Street Journal article, "An Eye for an Eye?"^(1)^.


# Section 2 - Scenario B

## The scenario

This scenario imagines that we are analysts at the Texas Department of Criminal Justice reporting to senior management in the department.

## General assumptions

I have assumed that there is no particularly special context for this reporting, and that it represents an annual report of execution data as part of normal reporting to management. There are certain legal requirements for what must be reported and so these need to be included in the work.

However, outside of these requirements, senior management are aware of media coverage of racial tensions between police and public across the US, and will likely want to focus on this issue as part of their overall report. They are also aware of several "botched executions" that have gathered further negative attention in the press, and they are keen to be made aware of any such events in Texas.

As such, I have assumed that further data are available beyond what was provided in the assignment, specifically information about supplies of execution material and the amount of time it took for each offender to die.

I have assumed that the report will be presented in PowerPoint format before being circulated as a document.

## Context

### Reason

Within this scenario, I imagined that the following intrigue might present (a) reason(s) for creating the visualisation. 

* __Audience intrigue__: Senior management are interested in the execution data within the context of the yearly report. Given the racial issues that they are concerned with, they are interested in knowing about the execution statistics broken down by racial group, covering questions such as "what proportion of executed offenders were non-white?" or "how has the racial breakdown of executed offenders changed over time?". Concerns over the possibility of a "botched execution" could be addressed by a presentation of average time-to-die data addressing topics such as "they may be interested in knowing how long it took, on average, for inmates to die this year compared to the last [X] years".


### Circumstances

* __Stakeholders__: The main stakeholders in this scenario are the audience - the senior management. Data must be presented to them, and concerns that they have about racial demographics and botched executions must be addressed. The head of the analytics team is also a stakeholder as they will need to ensure that the work is accurate, as well as meeting senior management needs. Other Department of Criminal Justice staff will also be stakeholders as they may have data that would be valuable (e.g. relating to supplies or time-to-die information) and may be able to provide further context to data that will be needed when presenting to senior management.

* __Audience__: The audience is exclusively senior management, the report is internal and will not be widely circulated. The audience is informed and sophisticated, I have assumed that the management have spent many years working in the department and can understand more complex numerical summaries and graphical representations of the data (e.g. box plots, stacked bars, forecasts). The audience is engaged and require clear information from the report such that they are equipped to answer questions to _their_ superiors in the future. However they are most focused on their concerns and so may have less time to spend on the "normal" data that must be in the report.

* __Pressures__: Given that this is an annual report, I have assumed that the analysts have 1 month to produce the report as part of their regular activities. They do not have extra budget beyond what is normal and so cannot do anything extraordinary. The report is internal only and as such the team needs only to emulate the internal style of reports and does not need to create a stand-out visual to "wow" anyone.

* __Rules__: The report must adhere to Texas DoJ internal standards. It must use the DoCJ standard-font and reporting colour palette and may not deviate from this. In terms of compatibility, the visualisations must be suitable for a PowerPoint-style presentation, as well as for printing within the report and therefore must fit within 1 sheet of A4 paper at their largest.

* __Frequency__: The report must be produced once per year. There are certain visuals that are produced each year and so must be reproducible given similar data (e.g. number of executions split by crime, for example) each year (and as such last year's report may be used as a template). Given management's specific concerns, a small number of visualisations will be more bespoke and will not necessarily require repeated production. The report is not live and will only be updated next year, and so no provision for frequent data refreshes is necessary.

* __Setting__: The setting is relatively rapid. Whilst management are interested in certain elements of the report, they are busy and will only look at details briefly - the visualisations need to be quick and punchy. The audience is a combination of live (during the presentation) and remote (when the report is circulated), therefore the visuals can require some explanation (in the presentation) but this explanation should be reproduced in text/explanatory call outs in the report.

* __Size__: The visualisation elements of the report will a series of (at most) 10 PowerPoint slides, therefore at most 10 visualisations should be created. Each visualisation must be view able on 1 slide and must be no larger than 1 side of A4 (either portrait or landscape) for when the report is printed. 

* __Format__: The visualisations will be formatted both as PowerPoint slides, and also as print handouts of the slides. They do not need to be interactive.

* __Creators__: There is a small (around 5 members) team of analysts in the Texas DoCJ comprising mainly technical analysts and statisticians. There is 1 senior analyst familiar with reporting within the DoCJ who will oversee the work. The team does not have a designer/illustrator or similar.

* __Tech__: The team is proficient with software such as Excel/Tableau (or similar) as well as languages such as R for both data manipulation and visualisation. No team member is proficient with bespoke tools such as `d3` or _Illustrator_.

## Vision

### Purpose

* __Experience__: The experience should be a mixture of explanatory and exhibitory. The standard reporting charts that must be produced can be almost entirely exhibitory in nature, simple presenting the data that the senior management will required - they are comfortable dealing with these charts and no further explanation is required. Charts focussing on senior managements specific concerns may need some explanation if they are non-standard chart types.

* __Tone__: The tone is very much reading. This is a dry, functional report. It is not seeking to excite or entertain senior management but merely to deliver the information that they require as efficiently as possible. Understanding will be driven through the delivery of facts, not through emotive responses.

## Ideas

Please note that my ideas in this section were partially inspired by information found on the _Death Penalty Information_ website^(2)^.


# Section 3 - Scenario C

## The scenario

This scenario imagines that we are part of a pressure group trying to influence the debate about the ending of capital punishment.

## General assumptions

I have assumed that the campaign group is _anti_-capital punishment and is seeking to influence the debate in order to achieve the end capital punishment. I assumed that the campaign group wants to focus on the inmates rather than on their crimes, and ideally to elicit some sympathy for them/the situation surrounding their crime(s) on a human/personal level. Moreover, I assumed that other data, such as average cost (per month) of holding an inmate on death row, were available or could be obtained within the timeframes of the project.

## Context

### Reason

Within this scenario, I imagined that the following intrigue might present (a) reason(s) for creating the visualisation. 

* __Anticipated intrigue__: In this context I imagined that the campaign group would anticipate the intrigue of audience along the lines of "If they are thinking about the abolition of capital punishment, they may be interested in knowing about the costs of holding a prisoner on death row, the amount of time prisoners spend on death row before being executed, the emotions of the inmate about to be executed or the amount of time it takes an inmate to die when they are executed." The campaign group wants to influence people and so is trying to anticipate what information will be most effective in doing so.

### Circumstances

* __Stakeholders__: In this scenario, I imagined that the stakeholders would be people such as the campaign manager(s) who must be kept "on side" whilst the project is ongoing. Other campaign/pressure groups may also be stakeholders if there is an element of collaboration. The Texas DoCJ may also be a stakeholder if the campaign group is seeking further data that is not readily available on the webpage provided in the assignment. There may need to be involvement of others who knew the inmates who would then also become stakeholders during journalistic work. The group might seek the advice of mental health professionals to help when profiling individuals, potentially making them stakeholders too. 

* __Audience__: I have assumed that the audience is essentially the general public, who's mood/opinion the group seek to affect. I.e., the group is not seeking to _directly_ affect decision makers, but to sway others in order to create the political pressure that will do so. I have therefore assumed that the audience ranges from layperson with very little experience/information on the issues, to a more sophisticated reader who understands the subject well. The audience is not initially captivated (i.e. they have not necessarily sought out the work) and so it must draw them in quickly. However, given the potential range of audience, it must also provide scope for more depth in its message(s) once a reader is engaged. 

* __Pressures__: I have assumed that this will be a relatively large piece of work and as such 6 months are available in which to produce the piece. Whilst the group is organised, it is not especially rich and so the budget is very limited - the solution must be cheap and not rely on expensive technologies or large numbers of paid staff to complete it. It must be visually distinct and striking in an effort to get it to "go viral" and deliver its message the largest number of people possible (even those beyond Texas).

* __Rules__: The visualisation must be web-based and be optimised for a smart-phone/tablets as well as desktop/laptop viewing. There are no specific requirements around colour, font(s) or other branding. However the campaign group is keen to avoid gore-ish colours or overly-sensational themes and so would like to restrict the palette to a small selection of colours. The visualisation must be compatible with both Android and iOS as well as non-Internet Explorer desktop-based browsers (IE compatibility is desirable, but not a strict requirement).

* __Frequency__: The visualisation will initially use historic data but a mechanism for refreshing the data every 6 months must be built in to the solution. The visualisation will not be _live_, but will change over time as new data become available.

* __Setting__: The setting is remote and the solution should be rapid, but with the facility for a more prolonged examination if the user spends time with the solution. Given the audience, the initial message(s) should be clear and explained, with instructions for how to get more insight with time.

* __Size__: Two related but separate versions of the visualisation will be produced. One for mobile devices which will be smaller scale with reduced detail (due to the smaller screen size) and one for lap/desktops with more functionality for exploring the detail in the data. 

* __Format__: The output will be purely for the web, i.e. no print at all. The visualisation will be be landscape and will potentially have animated elements if this proves to be possible in the timeframes. 

* __Creators__: The core (i.e. paid) team for the visualisation is small: 2 data experts, 1 artist/designer/animator and 2 journalist-types to gather more information on the inmates. However, given the nature of the campaign group there is the potential to crowd-source certain elements of the project and bring on additional volunteers to help with the project. 

* __Tech__: The core team is proficient with advanced bespoke visualisation technology (e.g. `R` or `d3.js`) as well as custom animation tools and artistic programs (such as _Illustrator_). The data experts are comfortable doing data manipulation and cleaning tasks using a variety of programmatic and GUI-based approaches. More experience with other tools can be sourced from campaign group volunteers if required.

## Vision

### Purpose

* __Experience__: The experience will initially be explanatory, but with exploratory functionality built in to the solution, especially in the desktop version. The initial explanation should state exactly what is being shown in the visualisation, with interactive features to get more information on individual data points built in. 

* __Tone__: The overall tone should be feeling to elicit a strong emotional reaction which will ideally help the project to "go viral". Within the exploratory layer, there is room for some elements of reading, presenting more detailed information about individual inmates and/or comparisons with similar inmates.

## Ideas

Some of the ideas around highlighting individuals present on death row were inspired by the Marshall Project.^(3)^


# Section 4 - Scenario D

## The scenario

In this scenario the assignment asks what intrigues _me_ about the data, and what might I do with it if I had the chance.

## General assumptions

I have assumed that there is no particularly special context for this project, that it is simply something I would undertake in my free time to share on my blog, twitter or similar for my own personal satisfaction.

## Context

### Reason

* __Potential intrigue__: Within the context of this data, I am interested in the general sentiment of the last words of the individuals who have been executed. I wonder if there is commonality in sentiment across the entire data, or within groups in the data (e.g. based on race, age). I also wonder how this sentiment might shift with the amount of time the inmate spent on death row before being executed. 

### Circumstances

* __Stakeholders__: There are no specific stakeholders as part of this project. It would be something I might complete in my own time in order to satisfy my own curiosity.

* __Audience__: The audience is likely to be anyone who stumbled upon my blog/twitter page, or those with whom I specifically shared the project. Given who reads my blog/follows me on twitter, it is likely that the audience will be relatively sophisticated and may understand more detailed analysis. Similarly, I would expect that they would be relatively captivated, having chosen to visit my page and having read about the visualisation.

* __Pressures__: Any time constraints would be purely self imposed, and I think setting a limit of 1 month would be appropriate for the project. The budget would be £0.

* __Rules__: I would likely choose a muted and restricted colour palette, and a clean font compatible with my blog. Beyond this there would be no set rules for the project.

* __Frequency__: This would be a one-off project, using historical data only (i.e. not live).

* __Setting__: The audience would be remote, and the setting would be for a medium to long duration spent with the visualisation.

* __Size__: There would be 2 or 3 simple charts each fitting on to a single screen.

* __Format__: The project would either be a `Shiny` web-app built using `R` and hosted online, or a selection of static images for a special blog post on my analysis.

* __Creators__: The creation team would be comprised of just me.

* __Tech__: The technology available would be limited Excel, `R`, `Python`, a small amount of `CSS` and `HTML` and simple command line tools.

## Vision

### Purpose

* __Experience__: The experience would be explanatory, presenting the findings of my analysis and explaining what I had found. If a `Shiny` web-app was built, then some limited interactivity would be possible in the charts, but the overall experience would still be one of explanation, and the interactivity would be limited to filtering/getting some further explanation as opposed to deep explorations.

* __Tone__: The tone would be more reading than feeling. It would simple present the results of my exploratory analysis and not seek to generate any strong emotions in the audience.

## Ideas

# References

1. Wall Street Journal Article, "An eye for an eye" -  [http://www.washingtonpost.com/wp-srv/special/outlook/death-penalty/](http://www.washingtonpost.com/wp-srv/special/outlook/death-penalty/). Sourced 2016/02/09
2. Death penalty Information -  [http://www.deathpenaltyinfo.org/texas-1#sent](http://www.deathpenaltyinfo.org/texas-1#sent). Sourced 2016/02/09.
3. The Marshall Project [https://www.themarshallproject.org/next-to-die/tx](https://www.themarshallproject.org/next-to-die/tx).