SELECT COUNT(DISTINCT EV.ID) AS EVENTS
FROM
	EVENT EV
INNER JOIN
(
	SELECT DISTINCT OPERATOR_CODE
	FROM
		PERSON PERS
	LEFT JOIN -- SELECT * FROM
		PERSON_POSITION LINK
	ON PERS.ID = LINK.PERSON_ID
	LEFT JOIN -- SELECT * FROM
		POSITION POS
	ON LINK.POSITION_ID = POS.ID
	WHERE POS.DESCRIPTION = 'OWNER'
	AND (FIRST_NAME LIKE '%T%' OR LAST_NAME LIKE '%T%')
) OWNERS_T
ON EV.OPERATOR_CODE = OWNERS_T.OPERATOR_CODE

