-- FIND AVERAGE AMOUNT
-- SELECT AVG(AMOUNT) FROM PAYMENT

SELECT COUNT(DISTINCT I.FILM_ID) AS FILMS
/*
	 R.*
	,I.FILM_ID
	,P.AMOUNT
	,(SELECT AVG(AMOUNT) AS AVG_COST FROM PAYMENT)
*/
FROM
	RENTAL R
LEFT JOIN
	INVENTORY I
ON R.INVENTORY_ID = I.INVENTORY_ID
LEFT JOIN
	PAYMENT P
ON R.RENTAL_ID = P.RENTAL_ID
WHERE P.AMOUNT >= (SELECT AVG(AMOUNT) AS AVG_COST FROM PAYMENT)
