SELECT DISTINCT
	TITLE
FROM
	FILM
WHERE FILM_ID IN
(
	SELECT DISTINCT FILM_ID
	FROM
		RENTAL R
	LEFT JOIN
		INVENTORY I
	ON R.INVENTORY_ID = I.INVENTORY_ID
	WHERE CAST(RETURN_DATE AS DATE) BETWEEN '2005-05-29' AND '2005-05-30'
)
