/* DROP INDICES AHEAD OF CREATION *********/
DROP INDEX IF EXISTS CONTACTS_IDX, LINES_IDX, ORDER_IDX;

/* CREATE INDICES TO HELP SPEED UP QUERIES *********/
CREATE INDEX CONTACTS_IDX 
   ON contacts (cust_id ASC NULLS LAST, contact_date ASC NULLS LAST);

CREATE INDEX LINES_IDX
   ON LINES (CUST_ID ASC NULLS LAST, ORDERNUM ASC NULLS LAST, ORDER_DATE ASC NULLS LAST);

CREATE INDEX ORDER_IDX
   ON ORDERS (CUST_ID ASC NULLS LAST, ORDERNUM ASC NULLS LAST, ORDER_DATE ASC NULLS LAST);