---
title: "BS0926 Work Placement"
author: "Jim Leach"
output: pdf_document
---

# Proposal Documentation

## Key Details

* __Company__: Sainsbury's (London, Digital & Technology, [http://www.sainsburys.work/](http://www.sainsburys.work/))
* __Supervisor__: Enda Ridge, Algorithms Lead ([enda.ridge@sainsburys.co.uk](mailto:enda.ridge@sainsburys.co.uk))
* __Position offered__: Data Scientist
* __Start date__: 13^th^ June 2016^(1)^
* __End date__: 22^nd^ July 2016
* Full time, paid.

## Overview of position

This six week internship will see me acting as a data scientist within the digital and technology department at Sainsburys. The role will involve helping to scope and deliver business-led analyses and projects, working in a small team with other members of the department.

The role will require me to translate business challenges into hypotheses and experiments. I will use machine learning, statistics, visualisations, and other analytical techniques in order to address these challenges.

Developing relationships with internal customers will be important. There may be some involvement in helping to increase the awareness of data science across the business.

The position will require me to understand how to translate retail business problems into practical data science, implemented using industry-standard data science technologies (e.g. Python, R, SQL).

I will need to design and implement analyses that deliver practical, quantifiable business benefits. Managing project demands and timelines will be critical. I will also need to maintain curiosity, scepticism and attention to detail regarding the data, the analyses, and the outcomes. 

I will be supported by the team lead and peers and will be provided with the technology required for the role. There may also be internal conferences and events that I can attend to help broaden my understanding of the business, and potentially to share the results of my work on the internship.

## Relevance to my career goals

My career goals are focussed on moving from a data analyst role towards a data science role, and this internship is perfect for helping me achieve that. 

With three years experience as a data analyst consultant, I understand the realities of working with data and want to develop into roles where I can begin to apply more of the advanced methods and scientific theories taught in the MSc. 

With a firm grounding in the practicalities of data science in the workplace, this role will therefore utilise my existing day-to-day skills and allow me to enhance my understanding of translating business problems into sophisticated analytical techniques, a critical skill for working in data science.

Furthermore, having the opportunity to implement these techniques will also be of great benefit in providing me the necessary practical work experience of working in a data science team in a business-led environment, delivering results that can have a real impact. 

Therefore, this role is of ideal relevance to my career goals.

## Notes

* (1) - An earlier start date to June 20^th^ was discussed with and approved by Jason Murray in an email dated 2016/04/08, which is submitted with this proposal.

***
