---
title: "BS1815 - Work Placement Summary"
output:
  html_document:
    toc: yes
    number_sections: yes
  pdf_document:
    fig_caption: yes
    number_sections: yes
    toc: yes
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Work Placement Details

* Candidate Name: James Leach
* Candidate Number: 01135629
* Work placement organisation: J. Sainsbury plc.
* Work placement dates: 2016/06/13 - 2016/07/22
* Work placement position: Adjunct Data Scientist, Algorithms Team

## Project summary

Teams within Sainsbury's use customer complaints in order to work with suppliers to address issues arising with their products. This work is ongoing, occurring on a weekly basis, and highly manual. The large number of complaints received for high-sales-volume departments, coupled with low-quality of the customer comments (for example, one/two-word complaints, or complaints with numerous typographical errors) makes this process difficult. Consequently, emerging and significant issues with products are hard to identify and time-consuming to resolve. 

I was responsible for a six-week project analysing the text of customer complaints, working for an internal client responsible for monitoring and resolving complaints. The goal was to develop automated, algorithmic methods for detecting topics from free-text complaint comments. The algorithm needed to be developed, trained and refined using a factorial experiment approach. Additional, business-led hypotheses were generated and tested using the topics detected. This enabled teams working with complaints data to better understand the complaints received and, crucially, to be able to take more focussed actions to remedy problems with suppliers. 

The project was highly successful. I developed, trained, and refined an algorithm that detected topics in millions of historical complaints. The algorithm ran end-to-end in around 20 minutes, which represented a significant reduction in time compared to current review methods (which can take up to 1.5 days per week for teams receiving a few _thousand_ complaints per week). The additional hypothesis testing was also very successful and generated several informative outcomes that were highly relevant to the business, and could be used to inform and improve their complaints-handling processes. The Algorithms team and the internal client were pleased with both my performance, and the results produced.

# Self Evaluation

## Knowledge Objectives

### Analysis of real, business related problems;

Improving customer satisfaction is a key business objective for Sainsbury's. Reviewing and resolving complaint issues is an important part of accomplishing this objective. The current business processes used to review complaints and resolve issues with suppliers are slow and highly manual. As such, any methods to better understand complaints are highly desirable and could help address a key business objective. Moreover, complaint volumes are a key metric used in performance monitoring and so helping to reduce them could significantly boost internal performance measures.

The results of my project, therefore, could have a significant impact on a real, business related problem that Sainsbury's deals with on a weekly basis. 

### Application of MSc. module knowledge to solve business tasks; and integration of theorectical knowledge with relevant practical skills

In order to solve the challenges presented on this assignment I had to use and integrate knowledge and skills obtained from the following MSc. modules:

* _Retail and Marketing Analytics_ - This module gave me an understanding of common terminology used in a retail context. This helped me to have conversations with other members of the team about projects that they were working on, and to make suggestions about aspects of their project that they had not considered. 

* _Very Large Data Management_ - I used skills from this module when creating a `PostgreSQL` database, loading data, performing sensible Extract, Transform and Load (ETL) steps in order to create a layered, relational data model; and to perform additional `SQL`-based data manipulations on the results obtained from topic-detection processes applied to customer complaint text.

* _Advanced Analytics and Machine Learning_ - I used the series of lectures given by Professor Benoit as a basis for the main body of work involving text analysis. I used `R` and Prof. Benoit's `quanteda` package to detect and create topics across complaints for thousands of product categories using collocation analysis, a method specifically discussed in class. I also explored other methods for topic detection discussed in class, including Latent Dirichlet Allocation, but discarded them due to their weaknesses in this specific context. 

* _Logistics and Supply Chain Analytics_ - I used time series methods (discussed in the module in the context of forecasting demand) in order to detect trends and potential seasonality in the time series of complaints received. I performed these analyses using the `forecast` package in `R` that was introduced in this module.

* _Digital Marketing_ - After detecting topics in the complaints, I used market-basket frequent-item-set mining techniques (the _apriori algorithm_) in order to detect co-occurrence of individual topics in a single complaint. Understanding the various metrics involved (e.g. _support_ and _confidence_ of an item-set) enabled me to use these methods in a different context to those for which they were presented in class. I used `SQL` to prepare the data and the `arules` package in `R` in order to implement the _apriori_ algorithm.

* _Network Analytics_ - I also used network analytics to detect clusters of individual topics when assessing the co-occurrence of topics on a single complaint. I used network centrality measures to understand the most important topics in a product category and community detection algorithms to find clusters in the graph structure. I performed these analyses using the `igraph` package, accessing its functionality from `R`.

* _Visualisation_ - I used knowledge from this module to select the most appropriate visualisation methods for my results, and to inform choices of how to structure and present these visualisations. I used the `ggplot2` `R` package discussed in class for the majority of my visualisations. I also used `D3.js` and other `JavaScript` libraries discussed in the second half of the module in order to produce interactive visualisations for my final presentation.

## Skills Objectives

### Completion of business-related tasks and analyses; and evaluation of results

TODO

During this project I completed many common business-related tasks, including meeting colleagues and clients, writing analytical code, producing visualisations and reporting my results. 

### Analysis of and interpretation of real-world business problems

Section 2.1.1 outlines the real-world business problem on this project. After meeting with the internal client I profiled the raw data and created some exploratory visualisations in order to understand how the data could be used to address the problem. I noted down and created exploratory plots of key attributes which helped me to interpret the problem from a data perspective. Understanding the data in this way enabled me to better analyse _why_ the real-world business problem was hard to solve and, therefore, what steps the algorithm I was developing would need to take. By analysing the interpreting the problem "from the data" I was better able to real-world significance of my work, and produce results that would be best-suited to resolving it.

### Management of line manager's, peer, and clients' expectations

At the beginning of the project my line manager and I met to discuss his expectations for me, and how I could achieve them. In the first week I met the internal client in order to understand their expectations for the project. I managed these expectations by attending daily stand-up meetings with my line manager and other members of the Algorithms team to keep them up to date on my progress. I met with my line manager in the third week (of six) to discuss my performance and ensure that I was meeting their expectations. I provided weekly, written updates to the internal client in order to keep them informed. I also met with members of the client's team several times throughout the project, helping to manage their expectations and ensure that my results were relevant to them.

### Deliver value through the completion of tasks

The tasks I completed were of high value to both the internal client, and to the Algorithms team. 

The value to the client was in developing an algorithm that could massively reduce the amount of work necessary for reviewing complaints. It could cut days of manual work to just minutes for the algorithm to run end-to-end. The additional hypothesis testing that I performed was also of great value to the client, helping them to better understand complaints and related issues at a high level. The client will also crucially realise value in an enhanced ability to work with suppliers to resolve complaint issues quickly, ultimately leading to fewer complaints, i.e. more satisfied customers. Given that this is a key objective for Sainsbury's, this is a substantial "value-add" for this project.

The value to the Algorithms team was in the generation of several leads for further work in this area. The results of my project suggested several other potential projects that the internal client could undertake both with complaints data, and with other text data. Moreover, several other Sainsbury's teams have similar data or similar problems that could be resolved using approaches similar to those undertaken on this project. My successful delivery of this project is therefore of great value to the Algorithms team. 

## Learning Outcomes

### Problem solving skills

I solved problems on this project by:

* researching and reviewing different approaches to solving similar problems elsewhere;
* using experimental approaches to inform my decisions; and
* working collaboratively with my team, and with other Sainsbury's colleagues in order to resolve issues.

Some examples of the approaches are presented below.

__Research and review__: An initial problem on this project was the selection of an appropriate algorithm for detecting topics in complaint text. In order to solve this issue I consulted my lecture notes, and read articles both online and in scientific journals, and discussed the problem with the team I was working with. This gave me an understanding of what methods _could_ be used. I then performed some initial testing of these methods, evaluating them based on several factors including the quality of their results (i.e. how useful were the outputs for addressing the business issue) and their computational complexity. This enabled me to select the algorithm I would use to detect topics in the complaints. 

__Experimental approach__: After selecting the algorithm I was going to use, I then encountered another problem: how to aggregate complaints in order to detect the "best" topics possible. In order to address this problem, I implemented a simple factorial experiment. I compared the results from this experiment both quantitatively and qualitatively with other members of the team. I then selected the approach that had produced the 

__Working collaboratively__: I also encountered problems caused by the messy nature of the data that I was using (abbreviations, negations, synonyms etc.). After devising some simple methods to address these issues I validated my approach with colleagues in my team, and (crucially) with members of the team that I was working for. This approach worked well. I was able to solve the problem and inclusion of the team I was working for meant that my approach was best suited to their needs and solving their business problem.

### Analytics skills to select and use relevant information

For this project, the information to use was relatively well defined: historical customer complaints. However exactly which complaints, and where to obtain them from was a little unclear at the outset. I therefore met with the internal client to discuss exactly which complaints they were interested in, and which database(s) they were stored in. I consulted the documentation for the complaints storage database to understand which other data might be relevant. I then met with the data owner to understand what data they could provide, and how they could provide it. In this way I demonstrated the skills necessary to select and use data/information in the workplace. And I worked with several people to do so, understanding and obtaining the data that was relevant to the project. 

### Communication and presentation skills to produce a report

I produced a final written report incorporating my both analytical results and visualisations, and putting these results in to the business context that was critical for the internal client. In the report I ensured that I was succinct and to the point. I provided: a brief executive summary; a description of the background to the project; the challenges facing the project; a description of my approach; the results I had produced; and a set of recommended next steps for taking the project further. Both my line manager and peers in the Algorithms team reviewed the draft of this report, enabling me to make changes and improve the report before delivering it to the internal client.

I also gave a major presentation to the internal analytics community in my final week. For this I produced a separate presentation with interactive storyboard elements. My line manager reviewed this presentation to ensure that I was covering the necessary material and suggested some minor changes prior to the actual presentation. I presented my results and findings, and walked through the steps I had taken at various stages of the project. During this presentation I was engaging and communicated effectively to a large audience. This presentation was very successful, the audience was engaged and interested in the work that I had performed, and the Algorithms team received several requests for follow-on work from other departments based on this presentation. 

### Project management skills

__Initiate__: Formal project initiation was not required on my part: the project had been discussed and planned by the Algorithms team and its internal clients before my arrival at Sainsbury's. As such there was a well-defined statement of work for me to follow with a set of specific aims and requirements for the project. However, I did hold a meeting with the client and members of their team in my first week in order to better understand the project and discuss _how_ we were going to approach it.

__Perform__: As well as daily stand-up meetings held within the Algorithms team, I provided a weekly update slide to my team and the internal client detailing the status of the project. This weekly update was aligned to the statement of work, ensuring that set-requirements were met. This meant that my time and my client were kept informed of progress regularly, and any problems could be overcome or resolved in a timely fashion. I held meetings with the internal client throughout the project to ask questions, and present intermediate results to ensure that my work aligned to their objectives.

__Close__: I produced a final written report and delivered this to the internal client, walking them through the approach and the results. I presented my work to the internal analytics community. I wrote detailed documentation for handing over my work to other members of the Algorithms team and provided a method for automating the algorithm I had developed.

# Evidence list

Due to the commercially sensitive nature of the work I performed, I am unable to provide any documents from my work placement as evidence. Please see the Endorsement section for feedback provided by my line manager.

# Endorsement