---
title: "Very Large Data Management Lecture 1"
author: "Jim Leach"
date: "15 October 2015"
output: pdf_document
---

# A definition of big data?

Due to the hype of 'big data' there is a lot of uncertainty as to what it actually _is_. A good working definition is:

> Big data is any data that has become hard to really handle/process (with traditional methods).

There are many challenges associated with working with big data, including:

* Captutre;
* Curation;
* Storage;
* Search;
* Sharing;
* Transfer;
* Analysis; and
* Visualisation

## The 3 V's:

1. Volume - data are continually increasing over time. Often more limited by disk I/O bandwidth as opposed to raw storage space.

2. Velocity - Any online process (both web-based and, for example, sensor data) generates data almost continually. The speed with which it arrives means that there is the potential for missed opportunities if decisions are not made in (near) real time.

3. Variety - data come in many forms: relational, text (unstructured), seme-structured (e.g. `XML`), graphs, streaming etc. The challenge is not processing just any one of these types, but in linking them all together to derive meaning. 

4. An additional V is Veracity - there can be uncertainty in the data due to inconsistency, incompleteness, latency, ambiguities etc. 

## Data creation model

Previously, there were few producers of data, and many consumers. Now there are as many producers as there are consumers. 

***

# Cloud computing

Has many benefits:

* Cost & management - i.e. economies of scale, out-sourcing;
* Reduced time to deployment;
* Scalability;
* Reliability; and
* Sustainability - the hardware is not owned as does not need to be maintained.

Has several types: public cloud, private cloud, hybid (critical apps/data on private, non-critical public), cloud bursting (switching to cloud providers during peak load times).

Comprised of:

* Infrastructure as a Service (IaaS) - hardware related services e.g. storage or computational power (e.g. Amazon EC2, S3);
* Platform as a Service (PaaS) - cloud based development platforms, e.g. Google application engine, Microsoft Azure; and
* Software as a Service (SaaS) - complete software offering in the cloud, e.g. Salesforce CRM, Google Docs.

Key ingredients are:
* Service-Oriented Architechture (SOA);
* Utility computing (on demand computing);
* Virtualisation;
* SaaS;
* PaaS; and
* IaaS.

Depending on the service, different functionality and restrictions are provided or applied. E.g. Google App Engine has high level functionality (e.g. it scales automatically) but is more restrictive for developers. Amazon EC2 is incredibly simple with low level functionality ownly, but as a result can be more flexible.

### Virtualisation

Often uses Hypervisor. The concept ensures that apps are isolated from each other and therefore do not crash the overall/underlying phyrical system if they fail. 

Virtualisation is good for flexible resource management, esp. on CPU, reasonably well with RAM. Resource management of hard disk storage is still a challenge (esp. if apps want to read/write large amounts of data!)

