---
title: "Very Large Data Management Lecture 2"
author: "Jim Leach"
date: "26 October 2015"
output: 
  html_document:
    theme: readable
---

# Business Intelligence OLAP and OLTP

## Relational databases

Formally given sets $D_1, D_2, ... D_n$, a __relation__ $r$ is defined as a subset such that $D_1 x D_2 x ... x D_n$, i.e. a relation is a set of $n$ tuples. e.g.

`customer_name = {Jones, Smith, Curry}`

`customer_street = {Main, North, Park}`

Then:

` r = { (Jones, Main), (Smith, North), (Curry, Park)}`

i.e. `r` is a relation over customer_name and customer_street.

## Relation Schema

If $A_1, A_2, ..., A_n$ are defined as _attributes_ then $R = (A_1, A_2, ..., A_n)$ is a _relation schema_. e.g. `Customer_schema = (customer_name, customer_steet)`.

$r(R)$ is a relation on the relation schema R, e.g. `customer (Customer_schema)`. 

To put this more plainly:

* Attributes = columns;
* Tuples = rows; and
* Relation = table.

It is therefore possible to say that a _database_ is something that consists of multiple relations (tables). Information is broken up accross each relation (table) such that each relation stores one part of the information, e.g. the account relation, the depositor relation and the customer relation. Storing all information in one relation (table) is a poor choice as it would introduce repitition/duplication and/or the need for `NULL` values.

SQL sits on top of the database and operates using relational algebra. We use a _database management system (DBMS)_ to handle the database (e.g. DB2, Oracle, SQL-Server etc).

## OLTP vs. OLAP

### OLTP (Online Transaction Processing)

* User facing;
* Real time;
* Low latency;
* Highly-concurrent;
* Many, small transactions, often of a "standard" nature;
* Read and write the database;
* E.g. e-commerce, online banking, transaction databases.

### OLAP (Online Analytics Processing)

* Back end;
* Batch workloads;
* Low concurrency;
* Large, complex analytical queries, often ad-hoc;
* Often read data only;
* e.g. business intelligence, data mining etc.

## OLTP with OLAP

To solve the issue of a single database using both OLTP and OLAP, it is normal to have separate databases for each process. 

One OLTP database for user-facing, real time, high-volume applications and a second, separate OLAP database for data warehousing and large scale analytics.

The two are connected via an _ETL_ process (Extract, Transform, Load).

## Star Schema

Within the data warehouse, data are often organised by a __star schema__. In this set up there is:

1. A _fact_ table: a large accumlation of facts, e.g. sales. Often insert-only; and
2. A set of _dimension_ tables: smaller, static information that relates to the entities involved in the facts.


## Wharehouse models

Commonly:

* Relations (tables);
* Stars and snowflakes (a slowflake occurs when there are "chains" of dimensions in a heirarchy e.g. sales (fact) -> store (dim) -> city(dim) -> region(dim)); and
* Cubes

## Aggregates in Warehousing

In SQL there are many ways to aggregate using `GROUP BY`. When aggregation is performed, it is often termed a "roll up". The reverse, returning to detailed data, is termed a "drill down".

### The Cube

One form of rollup that is useful is the cube, a form of multi-dimensional rollup. The cube can be made of more than 2 dimensions, extending in to 3 or higher. For example, a cube could be used to assess sales as a function of product, month and region in a multi-dimensional cube.

Within a cube there are also multiple "cuboids" that represent individual sections of the overall cube. For example, to extend the sales analogy, there could be 2D cuboids that represent a combination of month and region, product and region or product and month. Similarly there are 1D cuboids of sales by product, region, or month. And there is a 0D ("apex") cuboid that is simply total sales.

In this way, cubes can be transformed in multiple ways to rollup to increasingly higher levels of aggregation, or "unpacked" to drill down in different ways.

Effectively, a cube is a pivot table, but the advantage of using on in an onlne setting is that more than 2 dimensions can be accomodated easily.

In SQL, the syntax for the `CUBE` operator is as follows:

```
SELECT [fields]
FROM [table]
WHERE  [clause]
GOUP BY CUBE(dim1, dim2, dim3)
```

This cube will compute the union of 8 different groupings:

1. dim1, dim2, dim3;
2. dim1, dim2;
3. dim1, dim3;
4. dim2, dim3;
5. dim1;
6. dim2;
7. dim3.

Cubes can be combined with the usual aggregate functions (e.g. `sum`, `count`, `max` etc) as well as the `having` clause.

## Data Warehouse Implementation

When warehouses are implemented several concepts are important:

* Monitoring - sending data to/from sources and how this will be done;
* Integrating - ETL - what is the process?;
* Processing - queries, indexing;
* Managing - metadata, design

Data sources can be other relational systems, flat files, IMS, VSAM, IDMS, WWW, news-wire etc. They must be incoporated on either an incremental or refresh basic.






