---
title: "BS1815 - Work Placement Summary"
author: "James Leach (01135629)"
fontsize: 11pt
geometry: margin=1in
output:
  pdf_document:
    fig_caption: yes
    number_sections: yes
    toc: yes
  html_document:
    number_sections: yes
    toc: yes
  word_document:
    toc: yes
date: '`r Sys.Date()`'
---

# Work Placement Details

* Candidate Name: James Leach
* Candidate Number: 01135629
* Work placement organisation: J. Sainsbury plc.
* Work placement dates: 2016/06/13 - 2016/07/22
* Work placement position: Adjunct Data Scientist, Algorithms Team
* Contact: Enda Ridge (Algorithms Lead) - [enda.ridge@sainsburys.co.uk](mailto:enda.ridge@sainsburys.co.uk)

## Project summary

Teams within Sainsbury's use customer complaints to work with suppliers to address product. This work is ongoing, occurring on a weekly basis, and highly manual. The large number of complaints received for high-sales-volume departments, coupled with the low quality of the comments (e.g. one/two-word complaints, or complaints with numerous typographical errors) makes this process difficult. Consequently, emerging and significant issues are hard to identify and time-consuming to resolve. 

As a member of the Algorithms team I was responsible for a six-week project analysing the complaint texts, working for an internal client responsible for monitoring and resolving complaints. The goal was to develop automated, algorithmic methods for detecting complaint topics. I developed, trained and refined the algorithm using a factorial experiment approach.

Additional, business-led hypotheses were generated and tested using the results. This helped teams working with complaints to better understand them and, crucially, enabled more focussed action to remedy issues with suppliers. 

The project was highly successful. The algorithm detected high-quality topics in millions of historical complaints. The algorithm ran end-to-end in around 20 minutes, representing a significant reduction in time compared to current review methods (which take up to 1.5 days per week for teams receiving a few _thousand_ complaints per week). The additional hypothesis testing was also very successful and generated several informative outcomes that were highly relevant to the business. 

# Self Evaluation

## Knowledge Objectives

### Analysis of real, business related problems;

Improving customer satisfaction is a key business objective for Sainsbury's. Reviewing and resolving complaint issues is an important part of accomplishing this objective. As such, any methods to better understand complaints are highly desirable and could help address a key business objective. Moreover, complaint volumes are a key metric used in performance monitoring and so helping to reduce them could significantly boost internal performance measures.

The results of my project, therefore, could have a significant impact on a real, business related problem that Sainsbury's deals with on a weekly basis.

### Application of MSc. module knowledge to solve business tasks; and integration of theorectical knowledge with relevant practical skills

I applied the following module knowledge in this project, and integrated this with a number of relevant practical skills:

* _Retail and Marketing Analytics_ - This module taught me common retail terminology. This helped me have conversations with other members of the team about their projects, to make ask questions and make suggestions, and to communicate in an effective manner. 

* _Very Large Data Management_ - I used technical skills from this module: creating a `PostgreSQL` database, loading data, performing sensible Extract, Transform and Load (ETL) steps to create a layered, relational data model; and to perform complex `SQL` data manipulation relevant to the project.

* _Advanced Analytics and Machine Learning_ - I used the series of text analysis lectures given by Professor Benoit as a basis for the main body of this project. I used the `R` language and Prof. Benoit's `quanteda` package to detect and create complaint topics using collocation analysis, a method specifically discussed in class. I also explored other methods discussed in class, including Latent Dirichlet Allocation, but discarded them due to comparably poor results.

* _Logistics and Supply Chain Analytics_ - I used time series methods in order to detect trends and seasonality in the complaints received. I used the `forecast` `R` package, along with theory that was introduced in this module.

* _Digital Marketing_ - I used market-basket mining techniques (the _apriori algorithm_) to build topic association rules from topics co-occurring in a single complaint. Understanding the theoretical quantities involved (e.g. _support_ and _confidence_) enabled me to use these methods in a different context to those for which they were presented in class. I used `SQL` to prepare the data and the `arules` `R` package to implement the _apriori_ algorithm.

* _Network Analytics_ - Creating a network of topics linked by their co-occurrence in complaints (e.g. A occurring with B, B occurring with C etc.), I used network centrality measures to understand the most important topics in a product category. I used community detection algorithms to find clusters in the network to combine complaint topics together in to higher-level categories. I performed these analyses using the `igraph` `R` package.

* _Visualisation_ - I used knowledge from this module to select the most appropriate visualisation methods for my results, and to inform choices of how to structure and present these visualisations. I used the `ggplot2` `R` package discussed in class for the majority of my visualisations. I also used `D3.js` and other `JavaScript` libraries discussed in the second half of the module in order to produce interactive visualisations for my final presentation.

## Skills Objectives

### Completion of business-related tasks and analyses; and evaluation of results

I completed many common, business-related tasks including: meeting colleagues and clients; writing analytical code; producing visualisations; and reporting my results. I also completed many different analytical steps including: reviewing raw data; creating exploratory visualisations; calculating descriptive statistics; and running statistical hypothesis tests to address business questions. I undertook other relevant tasks including building rapport with colleagues, managing expectations, dealing with important stakeholders and swiftly resolving any problems that occurred.

I used many methods to evaluate my results through experimental design. This included both qualitative reviews (either by myself, by peers in the Algorithms team, by my line manager, or by the internal client) and quantitative comparisons to compare differences in approaches. 

### Analysis of and interpretation of real-world business problems

After meeting with the internal client I profiled the raw data and created exploratory visualisations to understand how the data could be used to address the problem. 

I noted down and charted key attributes which helped me to interpret the problem from a data perspective. Understanding the data in this way enabled me to better analyse _why_ the real-world business problem was hard to solve and, therefore, what steps the algorithm I was developing would need to take. 

By analysing and interpreting the problem "from the data" I was better able to understand the real-world significance of my work, and produce results that would be best-suited to resolving it.

### Management of line manager's, peer, and clients' expectations

At the beginning of the project my line manager and I met to discuss their expectations for me, and how I could achieve them. In the first week I met the internal client in order to understand their expectations for the project. I managed line manager and peer expectations by attending daily stand-up meetings to keep them up to date on my progress. 

I met with my line manager in the third week (of six) to discuss my performance and ensure that I was meeting their expectations. I provided weekly, written updates to the internal client in order to manage their expectations. I also met with members of the client's team several times throughout the project, helping to manage their expectations and ensure that my results were relevant to them.

### Deliver value through the completion of tasks

The value to the internal client was in developing an algorithm that massively reduced the amount of work necessary for reviewing complaints. My work cut days of manual work to just minutes for the algorithm to run. The additional hypothesis testing was also of great value, addressing long-standing questions about complaints. 

The internal client will crucially realise value in an enhanced ability to work with suppliers to resolve complaint issues quickly, ultimately leading to fewer complaints, i.e. more satisfied customers. Given that this is a key objective for Sainsbury's, this is a substantial "value-add" for this project.

The value to the Algorithms team was in the generation of several leads for further work in this area. My results suggested several other potential projects that could be undertaken, both with complaints data and with other text data. Moreover, several other Sainsbury's teams have similar data or similar problems that could be resolved using approaches similar to those undertaken on this project. 

## Learning Outcomes

### Problem solving skills

I solved problems on this project by:

* researching and reviewing different approaches to solving similar problems;
* using experimental approaches to inform my decisions; and
* working collaboratively with my team and other Sainsbury's colleagues.

e.g.

__Research and review__: An initial problem was the selection of an appropriate algorithm. In order to solve this I consulted lecture notes, read articles online and in scientific journals, and discussed the problem with the Algorithms team. This gave me an understanding of what methods _could_ be used. I then performed initial testing of these methods, evaluating them based on several factors including how useful were the outputs for addressing the business issue, and their computational complexity. This enabled me to select and appropriate algorithm. 

__Experimental approach__: After selecting the algorithm, I then encountered another problem: how to aggregate complaints in order to detect the "best" topics. I implemented a simple factorial experiment. I selected an approach by comparing the experimental results quantitatively, and qualitatively with other members of the team.  

__Working collaboratively__: I also encountered problems caused by the messy data I was using. After devising simple methods to address these issues I validated my approach with my colleagues, and (crucially) with the internal client. I solved the problem and inclusion of the team I was working for meant that my approach was best suited to solving their business problem.

### Analytics skills to select and use relevant information

The information to use was well defined: historical customer complaints. However exactly which complaints, and where to obtain them from was a little unclear at the outset. I therefore met with the internal client to discuss exactly which complaints they were interested in, and which database(s) they were stored in. I consulted the documentation for the storage database to understand which other data might be relevant. I met the data owner to understand what data they could provide, and how they could provide it. In this way I demonstrated the skills necessary to select and use data/information in the workplace.  

### Communication and presentation skills to produce a report

I produced a written report incorporating my analytical results and visualisations. The report put my results in to the business context critical for the internal client. I provided: 
* a brief executive summary; 
* a description of the background to the project; 
* the challenges of the project; 
* a description of my approach; 
* the results I had produced; and 
* a set of recommended next steps. 

Both my line manager and peers in the Algorithms team reviewed the draft of this report, enabling me to make changes and improve the report before delivering it to the internal client.

I also gave a major presentation to the internal analytics community in my final week. I produced a separate presentation with interactive storyboard elements. My line manager reviewed this presentation to ensure that I was covering the necessary material. I presented my results and findings, and walked through the steps I had taken. I was engaging and communicated effectively to a large audience. The presentation was very successful. The audience was engaged and interested in the work that I had performed, and the Algorithms team received several requests for follow-on work from other departments based on this presentation. 

### Project management skills

__Initiate__: Formal project initiation was not required on my part: the project had been discussed and planned before my arrival. However, I did hold a meeting with the client and members of their team in order to better understand the project and discuss _how_ we were going to approach it.

__Perform__: As well as daily stand-up meetings, I provided weekly update slides detailing the project status. This meant that my team and the client were kept informed of progress, and any problems could be rapidly overcome. I held meetings with the internal client throughout the project to ask questions, and present intermediate results to ensure that my work aligned to their objectives.

__Close__: I produced a final report and delivered this to the internal client, walking them through the approach and the results. I presented my work to the internal analytics community. I wrote detailed documentation for handing over my work to other members of the Algorithms team and provided a method for completely automating the algorithm I had developed.

# Evidence list

Due to the commercially sensitive nature of the work I performed, I am unable to provide any documents from my work placement as evidence. Please see the Endorsement section for feedback provided by my line manager.

***

# Endorsement

> __Impact__:

> It is my belief that for enterprise data science to be relevant and successful, it must be focused on well defined business objectives and outcomes while balancing the need for practicality with sophistication of modelling etc. Jim has leveraged his MSc technical skills and consulting background to good effect. The impact of his work is that it:

> * Showed Sainsbury’s the potential value hidden in complaints narratives;
* Allowed the business to rigorously test some long standing hypotheses around complaints, suppliers and products;
* Set a high standard for data science designed experiments, statistical evaluation of hypotheses and communication of results in a newly forming team; and
* Helped raise awareness of data science and its ability to discover quantifiable opportunities when implemented in a business-focused way.

> __What Jim did__:

> Jim’s work was two-fold. He first designed experiments to find and tune an appropriate algorithm for extracting structured content from raw complaint text narratives. He then applied a range of statistical tests to this data to test a set of business hypotheses about our complaints, our products and our suppliers. To achieve this, Jim:

> * Met with the internal customer to understand the business issue and where to get the data from;
* Read the documentation for the storage database and met with the data owner to understand exactly what data was available and how to obtain it;
* Obtained the data, loaded it in to the analytics environment and performed completeness checks;
* Profiled and explored the data;
* Discussed the data profile and the algorithmic approach with the internal customer;
* Implemented several candidate algorithms for topic detection (e.g. LDA vs. collocation methods);
* Refined the algorithm via a small factorial experiment varying the data aggregation level and algorithm type, and reviewed the results qualitatively and quantitatively;
* Implemented a matching method to tag complaints with relevant topic(s);
* Ran a second experiment to review a sample of tagged complaints with the internal customer;
* Used simple hypothesis tests to analyse the results of the review, and found which complaint attributes most affected quality (appeared to be negations);
* Refined the algorithm further by handling negations, correcting typos and dealing with known phrases (e.g. best before date);
* Incorporated the algorithm in to an automated, L0-L5 build following Guerrilla Analytics principles;
* Held several meetings with members of the internal customer’s team in order to better understand the current complaints processes and what might be useful hypotheses to test;
* Held brainstorming session with algorithms team to generate hypotheses to test;
* Conducted hypothesis testing (6 hypotheses) on output from the algorithm;
* Generated appropriate summary visualisations from the algorithm, and from the results of the hypothesis testing, choosing appropriate (technical) methods and (visual) formats to do this;
* Wrote and refined a final report and delivered it to the internal customer in a formal meeting;
* Wrote and presented a summary of the project, delivering the presentation to the Sainsbury's analytics community; and
* Closed-out the project with hand-over documentation and a read-me file.</p>

— <cite>Enda Ridge, Algorithms Lead, Sainsbury's</cite>. [Contact](mailto:enda.rige@sainsburys.co.uk).

