---
title: "Visualisation Assignment 2a"
author: "Jim Leach"
date: "16 February 2016"
output: pdf_document
---

# Introduction

## Background

This assignment deals with developing a solution to an editorial perspective proposed in an earlier assignment (1b). Data were provided covering Olympics medal winners for a range of Olympic years and events. The task was to to use Tableau to create a dashboard that set out an editorial perspective that could be taken with the data. Note that only the first data set was used.

## Document structure

This document is structured in to four sections. Each visualisation contained in the dashboard (of which there are three) is discussed in an individual section. The final section briefly summarises the overall dashboard.

# Design Decisions

## Visualisation One - Total medals by country

This visualisation shows the total medals won by all countries across the entire time-span that the data cover. It uses the area mark (with the position of each area being constrained by geographical realities). It uses the brightness/luminosity channel to represent the total number of medals won by each country. Greyscale was used in order that the map remain visually distinct from the other, coloured visualisations on the dashboard. The other visualisation display athlete-level data, and the map is country-level. Retaining a separate colour scheme for map and the others helps to reinforce that they do not display identical data. The legend provides detail about the relative values. A continuous colour was chosen as the scale of the data means that they are effectively continuous (even if only a discrete number of medals can be won) and a continuous colour scale best represents this.

A chloropleth map like this was chosen as it is appropriate for showing geographical data that is broken down by region in this way. Countries are [limited](https://www.quora.com/How-does-the-IOC-determine-how-many-athletes-a-country-can-send-to-the-Olympics) in the number of athletes they can send per event. Therefore the map quickly shows which countries are the "heavy-hitters" in terms of total medals won, and is not obscured by the relative sizes of country populations.

Within the map itself, a user can zoom and pan to manipulate the visualisation if they are interested in a particular geographical region (e.g. Europe or Asia). The map also acts as a filter for the other visualisations. Selecting a country (or countries) filters the other visualisations to display just data for the selected countries, allowing a more granular view of the data to be seen. This decisions was made as the map is the "top level" visualisation. It is a natural filter point for the more granular, athlete level, data beneath it.

## Visualisation Two - Total medals by athlete

This visualisation shows the total number of medals won by each individual athlete, for all athletes in the data. It uses the lines (bars) visual mark as well as the text mark to add extra detail for each athlete (their gender and sporting discipline). The _length_ visual channel is used to show the number of medals won by each athlete. Colour is not used to encode any data (i.e. it is used purely for decorative purposes), with all bars coloured in an identical manner. As well as helping make this visual distinct from the map (which shows a different view of the data), the use of colour adds some visual appeal which can be helpful in creating a favourable visual product.

A barchart was chosen as it is effective for displaying count data broken for individual groups/units. It is a well-known chart type that is easy to read. The horizontal layout makes it easy to read the athlete names, as well as the detail on gender and sport, which is why it was chosen. The barchart also makes it easy to see differences in the total number of medals won by athletes in order to find the all-time best athletes (in terms of total medals) across all countries. Similarly, once visualisation one has been used to filter to just those athletes for a specific country, it is easy to identify stand-out successes within a country's team. 

The decision to add gender and sporting discipline as a label was taken as they add extra detail without cluttering the overall visual. Users can quickly get a sense of which disciplines have produced hugely successful athletes, as well as an idea of how men and women compare when it comes to total medals won. 

Hovering over an individual athlete highlights their country of origin in visualisation one, as well as their position in visualisation three (athlete efficiency). The decision to implement the linkage with the map was made as it allows a user to quickly view an athlete's home country without performing filtering. 

The linkage to the third visualisation gives more detail. A user has a better idea of how successful the athlete is from an efficiency perspective (i.e. how many medals they have won relative to how many appearances they have made). This highlighting allows athletes with an equivalent total-medal count to be compared by viewing their position on the efficiency chart via the highlighting interaction.

It was decided that this chart should only highlight and not filter the other visualisations. Filtering the other charts to individual athletes threw away too much data from the dashboard and removed the context necessary to understand an athlete's success.

## Visualisation Three - Athlete efficiency (Medals vs. Appearances)

This visualisation shows the relationship between the total number of medals won by an athlete and the number of times they have competed at the Olympics. This is a measure of athlete efficiency. 

The visualisation uses the point visual mark to plot each athlete on the chart. The position of each point encodes each athlete's efficiency (with positions in the top-left of the visualisation representing more efficient athletes). A scatter plot was chosen as it is the most effect visualisation for viewing the relationship between two numerical variables.

Many athletes sit at the same positions on this chart (as both medal count and appearances are discrete numbers) and so saturation/transparency has been used to give a sense of where the bulk of athletes are positioned on this graph. I.e. it encodes the number of athletes at each position on the chart. Again the exact colour does not encode any data and has been used merely for aesthetic reasons and to add visual appeal. The same colour as visualisation two was used to help visually tie them together, as they present different views of the same data.

Selecting a point (or group of points) in visualisation three will filter both visualisation one _and_ two to display just the data relevant to that point/points. This allows more information about groups of similarly-efficient athletes to be viewed. It was decided that filtering should be used for visualisation three as a user may want to hone in specific groups of athletes within this chart and filtering enables this to be done more smoothly than highlighting.

## The overall dashboard

This dashboard uses three distinct but common (and hence read-able) chart types: a chloropleth map, a simple barchart and a scatterplot. Each visualisation enables a different angle of the data to be viewed. Reading from left-right, top-bottom the data tell an increasingly detailed story and it was a conscious decision to arrange the different charts in this manner. 

The first, country level view, gives a quick overview. Next, the user sees an athlete-level view. This gives more information about the individual athletes who have won medals (perhaps from a particular country if the first visualisation has been used to filter). The third and final visualisation gives even more detail about the individual athletes. It reveals not just their raw performance (total medals) but their efficiency (medals vs. appearances). 

The interactivity that has been introduced in to the dashboard means that a user can filter and highlight in order to manipulate each of these angles. In doing so, further understanding can be gained, and clarity is developed. The limited colour palette helps to keep the visualisation clean and simple and to tie elements together. 








