---
title: "Statistics and Econometrics - Assignment Three"
author: "Jim Leach"
date: "28 October 2015"
output: pdf_document
---

# Document purpose

The purpose of this document is to write up the response to the third assignment given as part of the _Statistics and Econometrics_ module. It is divided in to two sections, each covering a section of the assignment as given. Each major section is divided in to further subsections, one for each question in the assignment.

A number of `R` packages have been used throughout this assignment. These are loaded before the responses are given:

```{r load_pkg, echo = TRUE, message = FALSE}
library(dplyr)
library(magrittr)
library(broom)
library(knitr)
```

***

# Section 1

In this section, it is posited that data from a survery on wages, education, experience and gender is provided. In addition, data on marijuana use is also asked for. The question asked regarding marijuana use was:

> "On how many separate occasions last month did you smoke marijuana?"

## 1a

\begin{equation} \label{eq:1a}
log(wage) = \beta_0 + \delta_1 female + \beta_1 education + \beta_2 experience + \beta_4 marijuana + u
\end{equation}

If it is assumed that:

* gender is represented by a binary variable (named $female$) whereby a value of $1$ indicates female, and $0$ indicates male; and
* education, experience and marijuana are purely quantitaive variables named as such

then a simple equation such as \eqref{eq:1a} can be written to allow statements such as "Smoking marijuana five more times per month is estimated to change wage by x%". Note that the dummy variable $female$ contrasts the change in wage between genders (holding the other independant constant) with males as the base group.

## 1b

\begin{equation} \label{eq:1b}
log(wage) = \beta_0 + \delta_1 female + \beta_1 education + \beta_2 experience + \beta_3 marijuana + \delta_2 marijuana.female + u
\end{equation}

The regression function given in \eqref{eq:1b} would allow a test to be performed to understand if drug (marijuana) use has a different effect on wage for men and women. In \eqref{eq:1b} it is the $\delta_2$ parameter that describes this effect, it is the estimated change in the slope coefficient for marijuana use ($\beta_3$) for females over the reference group (males).

It would be possible to test that there are no differences in the effects of drug usage for men and women using the following hypothesis:

* $H_0:\delta_1 = 0$ and $\delta_2 = 0$, i.e. the wage is the same for men and women who have the same level of drug use.

For this hypothesis, an $F$-statistic could be generated to test for exclusion restrictions. 

## 1c


\begin{equation} \label{eq:1c}
log(wage) = \beta_0 + \delta_1marijuana + \beta_1 education + \beta_2 experience
\end{equation}


In this example gender is omitted (for simplicity's sake), as are interaction terms between marijuana use and the other variables. It is assumed that marijuana use is given by a categorical factor variable with four levels:

1. nonuser (0 uses per month);
1. light user (1 to 5 uses per month);
2. moderate user (6 to 10 uses per month); and
4. heavy user (greater than 10 uses per month).

In the equation given by \eqref{eq:1c} the effect of marijuana use on wage is given by $\delta_1$. A fuller and more explicit regression function could also be given by:

\begin{equation} \label{eq:1c_2}
log(wage) = \beta_0 + \delta_0 light + \delta_1 medium + \delta_2 heavy + ... + u
\end{equation}

In equation \eqref{eq:1c_2}, the "..." term represents the other variables included in \eqref{eq:1c} but omitted here for brevity. In \eqref{eq:1c_2}, $\beta_0$ represents the estimated wage for nonusers holding the other variables constant, $\delta_0$ represents the change for light users, $\delta_1$ for medium users and $\delta_2$ for heavy users.

## 1d

To test the null hypothesis that marijuana usage has no effect on wage is done using an $F$ statistic. In this instance, _marijuana use_ is not well defined and as such it is assumed that this means that the null is that _any_ use of marijuana has no effect on wage. 

As such, this is best understood using \eqref{eq:1c_2} to test for multiple linear restrictions in the $\delta$ parameters of the marijuana dummy variable. To do so, an __unrestricted__ model is defined (again, gender is omitted for simplicity's sake).

\begin{equation} \label{eq:1d_ur}
log(wage) = \beta_0 + \delta_0 light + \delta_1 medium + \delta_2 heavy + \beta_1 education + \beta_2 experience + u
\end{equation}

In order to test the null that marijuana usage has no effect on wage it is also necessary to construct the __restricted model__ that describes this.

\begin{equation} \label{eq:1d_r}
log(wage) = \beta_0 + \beta_1 edcuation + \beta_2 experience + u
\end{equation}

The restricted model \eqref{eq:1d_r} will allow the null $H_0: \delta_0 = 0$ and $\delta_1 = 0$ and $\delta_2 = 0$ to be tested.

In order to do this, the $F$ statistic is computed.

\begin{equation} \label{eq:1d_fstat}
F = \dfrac{(SSR_r - SSR_{ur})/q}{SSR_{ur}/(n-k-1)}
\end{equation}

In \eqref{eq:1d_fstat} $SSR_r$ and $SSR_{ur}$ represent the sum of squared residuals from the restricted and unrestricted models respectively, $q$ is the number of restrictions and $n-k-1$ is the degrees of freedom in the unrestricted model. 

Having calculated the $F$ statistic, a critical value is defined for the desired significance level using an $F$ distribution with $df1 = q$ and $df2 = n-k-1$. If the $F$ statistic calulcated is greater than or equal to this critical value then the null can be rejected, i.e. it is possible to state that marijuana use _does_ have a statistically significant effect on wage. This is independant of an individual dosage of marijuana (i.e. light/medium/heavy) and instead considers the __joint effect__ of the three doses on wage.

## 1e

Some potential problems with drawing causal inferences using the survey data collected are self selection problems. It may be the case that people who use marijuana are less likely (or more likely) to respond to the survey, leading to a potentially biased sample. 

Furthermore, there may be issues of multicollinearity between marijuana use and the other explanatory variables (for example it may be the case that men are more likely to use marijuana, or that people who use marijuana have lower levels of education on average).

Moreoever, there may be many variables that are included in the error term that have a (high) correlation with marijuana use (e.g. socio-economic status, ethnicity) but that could have a significant impact on wage. By not explicitly including these in the model it is possible that the ZCM assumption will not hold and as such it could be hard to draw causal inferences from the data.

***

